NUM_LOCATIONS = 30
NUM_GENERATIONS = 35000
POPULATION_AMOUNT = 50

ELITE_AMOUNT = 3  # amount of individuals carried over to next generation
SELECTION_METHOD = "Roulette-Wheel"  # Roulette-Wheel or Linear Rank (TODO)

# Chances of mutations are mutually exclusive,
# also they run from lowest to highest probability,
# meaning if i.e. a 0.05 chance mutation happens,
# then a 0.10 chance mutation won't happen in that same case.
CHANCE_SHUFFLE_MUTATION = 0.05
CHANCE_SEQUENTIAL_SWAP_MUTATION = 0.15
CHANCE_RANDOM_SWAP_MUTATION = 0.25

# These are actually male dog names... but that doesn't matter.
LOCATION_NAME_LIST = [
    "Ace",
    "Apollo",
    "Bailey",
    "Bandit",
    "Baxter",
    "Bear",
    "Beau",
    "Benji",
    "Benny",
    "Bentley",
    "Blue",
    "Bo",
    "Boomer",
    "Brady",
    "Brody",
    "Bruno",
    "Brutus",
    "Bubba",
    "Buddy",
    "Buster",
    "Cash",
    "Champ",
    "Chance",
    "Charlie",
    "Chase",
    "Chester",
    "Chico",
    "Coco",
    "Cody",
    "Cooper",
    "Copper",
    "Dexter",
    "Diesel",
    "Duke",
    "Elvis",
    "Finn",
    "Frankie",
    "George",
    "Gizmo",
    "Gunner",
    "Gus",
    "Hank",
    "Harley",
    "Henry",
    "Hunter",
    "Jack",
    "Jackson",
    "Jake",
    "Jasper",
    "Jax",
    "Joey",
    "Kobe",
    "Leo",
    "Loki",
    "Louie",
    "Lucky",
    "Luke",
    "Mac",
    "Marley",
    "Max",
    "Mickey",
    "Milo",
    "Moose",
    "Murphy",
    "Oliver",
    "Ollie",
    "Oreo",
    "Oscar",
    "Otis",
    "Peanut",
    "Prince",
    "Rex",
    "Riley",
    "Rocco",
    "Rocky",
    "Romeo",
    "Roscoe",
    "Rudy",
    "Rufus",
    "Rusty",
    "Sam",
    "Sammy",
    "Samson",
    "Scooter",
    "Scout",
    "Shadow",
    "Simba",
    "Sparky",
    "Spike",
    "Tank",
    "Teddy",
    "Thor",
    "Toby",
    "Tucker",
    "Tyson",
    "Vader",
    "Winston",
    "Yoda",
    "Zeus",
    "Ziggy"
]